#!/usr/bin/env python3
"""
Turn a file into a MicroPython module that holds its bytes.

MicroPython's freezer only picks up .py/.mpy files, so anything else in src/
(images, index.html) never makes it into a release .uf2. Converting such a
file into a module with a single `DATA = b'...'` literal fixes that: once
frozen, the bytes object is flash-resident, so importing it costs no RAM
beyond the module dict - unlike reading the file into a buffer at runtime.

Usage:
    tools/freeze_file.py <source-file> <output-module.py>
"""

import os
import sys

# Bytes per source line. Purely cosmetic: adjacent bytes literals are
# concatenated by the compiler into one object.
CHUNK = 48


def freeze(src_path, out_path):
    with open(src_path, "rb") as f:
        data = f.read()

    name = os.path.basename(src_path)
    out = [
        "# Generated by tools/freeze_file.py from %s - do not edit by hand.\n" % name,
        "# %d bytes. Frozen into the firmware this literal lives in flash,\n" % len(data),
        "# so it costs no RAM until something copies it.\n",
        "DATA = (\n",
    ]
    if data:
        for i in range(0, len(data), CHUNK):
            out.append("    %r\n" % data[i:i + CHUNK])
    else:
        out.append("    b''\n")
    out.append(")\n")

    with open(out_path, "w") as f:
        f.writelines(out)
    return len(data)


def main(argv):
    if len(argv) != 3:
        print(__doc__.strip())
        return 2
    size = freeze(argv[1], argv[2])
    print("[freeze_file] %s -> %s (%d bytes)" % (argv[1], argv[2], size))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
